motekarteknologi/motekarteknologi/ViewModels/Modal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace motekarteknologi.ViewModels
{
    public class Modal
    {
        public string ID { get; set; }
        public string AreaLabelID { get; set; }
        public ModalSize Size { get; set; }
        public string ModalSizeClass
        {
            get
            {
                switch (this.Size)
                {
                    case ModalSize.Small:
                        return "modal-sm";
                    case ModalSize.Large:
                        return "modal-lg";
                    case ModalSize.Medium:
                    default:
                        return "";
                }
            }
        }
    }
}

motekarteknologi/motekarteknologi/ViewModels/ModalFooter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace motekarteknologi.ViewModels
{
    public class ModalFooter
    {
        public string SubmitButtonText { get; set; } = "Submit";
        public string CancelButtonText { get; set; } = "Cancel";
        public string SubmitButtonID { get; set; } = "btn-submit";
        public string CancelButtonID { get; set; } = "btn-cancel";
        public bool OnlyCancelButton { get; set; }
    }
}

motekarteknologi/motekarteknologi/ViewModels/ModalHeader.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace motekarteknologi.ViewModels
{
    public class ModalHeader
    {
        public string Heading { get; set; }
    }
}

motekarteknologi/motekarteknologi/Controllers/ModulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using motekarteknologi.Motekar;
using motekarteknologi.ViewModels;

namespace motekarteknologi.Controllers
{
    [Authorize]
    public class ModulesController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            List<Module> modules = new List<Module>();
            foreach (var item in Modules.All)
            {
                modules.Add(new Module {
                    Name = item,
                    Description = item,
                    Controller = "Dashboards",
                    Action = "Index",
                    Role = item,
                    Area = item.Replace(" ", "")
                });
            }
            return View(modules);
        }

        [Authorize(Roles = Motekar.Modules.Security)]
        public IActionResult Security()
        {
            return View();
        }

        [Authorize(Roles = Motekar.Modules.CRM)]
        public IActionResult CRM()
        {
            return View();
        }

        [Authorize(Roles = Motekar.Modules.Inventory)]
        public IActionResult Inventory()
        {
            return View();
        }

        [Authorize(Roles = Motekar.Modules.SO)]
        public IActionResult SalesOrder()
        {
            return View();
        }

        [Authorize(Roles = Motekar.Modules.PO)]
        public IActionResult PurchaseOrder()
        {
            return View();
        }

    }
}

motekarteknologi/motekarteknologi/Areas/security/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - motekarteknologi</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Modules" asp-action="Index" class="navbar-brand">motekarteknologi</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @foreach (var item in SecurityModules.All)
                    {
                        if (User.IsInRole(item))
                        {
                            <li><a asp-area="Security" asp-controller="@item.Replace(" ","")" asp-action="Index">@item</a></li>
                        }
                    }

                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - motekarteknologi</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

motekarteknologi/motekarteknologi/Areas/security/Views/Shared/_Modal.cshtml
@model Modal

<div aria-hidden="true" aria-labelledby="@Model.AreaLabelID" role="dialog" tabindex="-1" id="@Model.ID" class="modal fade">
    <div class="modal-dialog @Model.ModalSizeClass">
        <div class="modal-content">
        </div>
    </div>
</div>

motekarteknologi/motekarteknologi/Areas/security/Views/Shared/_ModalDelete.cshtml
@model String

@using (Html.BeginForm())
{
    @Html.Partial("_ModalHeader", new ModalHeader { Heading = "Delete" })

    <div class="modal-body form-horizontal">
        Are you want to delete @Model?
    </div>
    @Html.Partial("_ModalFooter", new ModalFooter { SubmitButtonText = "Delete" })
}

motekarteknologi/motekarteknologi/Areas/security/Views/Shared/_ModalFooter.cshtml
@model ModalFooter

<div class="modal-footer">
    <button data-dismiss="modal" id="@Model.CancelButtonID" class="btn btn-default" type="button">@Model.CancelButtonText</button>
    @if (!Model.OnlyCancelButton)
    {
        <button class="btn btn-success" id="@Model.SubmitButtonID" type="submit">
            @Model.SubmitButtonText
        </button>
    }
</div>

motekarteknologi/motekarteknologi/Areas/security/Views/Shared/_ModalHeader.cshtml
@model ModalHeader
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">@Model.Heading</h4>
</div>

motekarteknologi/motekarteknologi/Areas/security/Views/Shared/_ModalScriptsInit.cshtml
@model string

<script type="text/javascript">
    $(document).ready(function () {

        (function ($) {
            function ModalInit() {
                var $this = this;

                function initilizeModel() {
                    $("#@Model").on('loaded.bs.modal', function (e) {
                    }).on('hidden.bs.modal', function (e) {
                        $(this).removeData('bs.modal');
                    });
                }
                $this.init = function () {
                    initilizeModel();
                }
            }
            $(function () {
                var self = new ModalInit();
                self.init();
            })
        }(jQuery))


    });

</script>